% Computer Vision Project 3
% Turned in by <Michael Single>
% Legi: 08-917-445


% flush context
clc
clear all;
close all;
%% 
% load dependencies
run lib/vlfeat-0.9.19/toolbox/vl_setup 

addpath('util/');
addpath('lib/');
addpath('src/');

% should we use the breaking bad data set?
useBB = true;

% assumes that such a file exists, can be generated by running
% the function #computeSiftDataOf(..). See rawDescriptorMatches for its
% usage.
wordsPerCluster = 1500;

frameBaseName = 'video_test';
if useBB
    frameBaseName = 'breakingbad2';
end
allSiftFeaturesBase = strcat('data/',frameBaseName,'_all.mat');

load(allSiftFeaturesBase, 'allFrameNames', 'descrCount', 'allPos', ...
    'allOrients', 'allScales', 'allDescr');

%% Generate bag of worlds
[membership, means, rms] = kmeansML(wordsPerCluster, allDescr');
disp('Clustering data has been computed.');

%% Perform the full frame query
frameCount = length(descrCount);

% compute histograms
histData = computeFrameHisto(descrCount, membership, frameCount, wordsPerCluster);

% show best matchings for 3 random frames
randFrames = randperm(frameCount, 3);
for frameIdx = randFrames
    
    % find the best matchings (indices for corresponding frames and their
    % scores.
    [scores, idxs] = getSortedScores( histData(frameIdx, :), histData, frameCount);
    figure('name', 'Full Frame Queries')
    
    % show reference frame
    currSiftMatFile = strcat(frameBaseName, '_', num2str(idxs(1)), '.mat');
    [currentFrameName, featureCount, positions, ...
        orients, scales, descriptors] = loadOwnSiftDataOf(currSiftMatFile);
    img = imread(strcat('frames/',currentFrameName));
    subplot(2,3,1);
    imshow(img);
    
    % passe title
    tillIdx = regexpi(currentFrameName, '_');
    fraName = currentFrameName(tillIdx+1:end);
    tillIdx = regexpi(fraName, '.png');
    fraName = fraName(1:tillIdx-1);
    title(strcat('Selected Image ', fraName));
    
    % show all matching frames achieving the the best score to the
    % reference frame.
    for k=2:6
        % load frame data and show image.
        currSiftMatFile = strcat(frameBaseName, '_', num2str(idxs(k)), '.mat');
        [currentFrameName, featureCount, positions, ...
            orients, scales, descriptors] = loadOwnSiftDataOf(currSiftMatFile);
        img = imread(strcat('frames/',currentFrameName));
        subplot(2,3,k);
        imshow(img);
        
        % pase title name
        tillIdx = regexpi(currentFrameName, '_');
        fraName = currentFrameName(tillIdx+1:end);
        tillIdx = regexpi(fraName, '.png');
        fraName = fraName(1:tillIdx-1);
        title(strcat('Matching Imgage ', fraName, ' with score: ',num2str(scores(k))));
    end

end
