% Computer Vision Project 3
% Turned in by <Michael Single>
% Legi: 08-917-445


% flush context
clc
clear all;
close all;

% load dependencies
run lib/vlfeat-0.9.19/toolbox/vl_setup 

addpath('util/');
addpath('lib/');
addpath('src/');

% assumes that such a file exists, can be generated by running
% the function #computeSiftDataOf(..). See rawDescriptorMatches for its
% usage.

wordsPerCluster = 1500;
frameBaseName = 'video_test';
allSiftFeaturesBase = strcat('data/',frameBaseName,'_all.mat');
regSelCount = 4;

load(allSiftFeaturesBase, 'allFrameNames', 'allPos', ...
    'allOrients', 'allScales', 'allDescr');

[membership, means, rms] = kmeansML(wordsPerCluster, allDescr');
frameCount = length(descrCount);

%%
for t=1:regSelCount
    randFrameIdx = randi(frameCount);
    randSiftMatFile = strcat(frameBaseName, '_', num2str(randFrameIdx), '.mat');
    [currentFrameName, featureCount, positions, ...
        orients, scales, descriptors] = loadOwnSiftDataOf(randSiftMatFile);
    img = imread(strcat('frames/', currentFrameName));
    
    figure('name', strcat('selected image ', currentFrameName));
    maskedIndices = selectRegion(img, positions);
    maskedIdxDescr = descriptors(maskedIndices, :);
    
    % indices of selected descriptor in collection of all descriptors
    [~, selDescIdxs] = ismember(maskedIdxDescr, allDescr, 'rows');
    
    histSelFeatures = histc(membership(selDescIdxs), 1:wordsPerCluster)';
    histData = computeFrameHisto(descrCount, membership, frameCount, wordsPerCluster);
    
    normalizationFScale = sqrt(sum(histData.^2, 2));
    normalFrameF = (repmat(norm(histSelFeatures),frameCount,1).*normalizationFScale);
    scores = dot(repmat(histSelFeatures, frameCount,1), histData, 2);
    [scores, idxs] = sort(scores ./ normalFrameF, 'descend');
    
    for k=1:6
        currSiftMatFile = strcat(frameBaseName, '_', num2str(idxs(k)), '.mat');
        [currentFrameName, featureCount, positions, ...
            orients, scales, descriptors] = loadOwnSiftDataOf(currSiftMatFile);
        img = imread(strcat('frames/',currentFrameName));
        subplot(2,3,k);
        imshow(img);
        title(strcat('Matching Imgage', currentFrameName, 'with score: ',num2str(scores(k))));
    end
    
end