% Computer Vision Project 3
% Turned in by <Michael Single>
% Legi: 08-917-445


% flush context
clc
clear all;
close all;

% load dependencies
run lib/vlfeat-0.9.19/toolbox/vl_setup 

addpath('util/');
addpath('lib/');
addpath('src/');

% should we use the breaking bad data set?
useBB = false;

% assumes that such a file exists, can be generated by running
% the function #computeSiftDataOf(..). See rawDescriptorMatches for its
% usage.
wordsPerCluster = 1500;
regSelCount = 1;

frameBaseName = 'video_test';
if useBB
    frameBaseName = 'breakingbad2';
end

allSiftFeaturesBase = strcat('data/',frameBaseName,'_all.mat');
load(allSiftFeaturesBase, 'allFrameNames', 'descrCount', 'allPos', ...
    'allOrients', 'allScales', 'allDescr');

%% compute cluster data
[membership, means, rms] = kmeansML(wordsPerCluster, allDescr');

%% perform region queries
frameCount = length(descrCount);
for t=1:regSelCount
    randFrameIdx = randi(frameCount);
    randSiftMatFile = strcat(frameBaseName, '_', num2str(randFrameIdx), '.mat');
    [currentFrameName, featureCount, positions, ...
        orients, scales, descriptors] = loadOwnSiftDataOf(randSiftMatFile);
    img = imread(strcat('frames/', currentFrameName));
    
    figure('name', strcat('selected image ', currentFrameName));
    maskedIndices = selectRegion(img, positions);
    maskedIdxDescr = descriptors(maskedIndices, :);
    figure('name', strcat('Matches of selection in ', currentFrameName));
    % indices of selected descriptor in collection of all descriptors
    [~, selDescIdxs] = ismember(maskedIdxDescr, allDescr, 'rows');
    
    histSelFeatures = histc(membership(selDescIdxs), 1:wordsPerCluster)';
    histData = computeFrameHisto(descrCount, membership, frameCount, wordsPerCluster);
    
    normalizationFScale = sqrt(sum(histData.^2, 2));
    normalFrameF = (repmat(norm(histSelFeatures),frameCount,1).*normalizationFScale);
    scores = dot(repmat(histSelFeatures, frameCount,1), histData, 2);
    [scores, idxs] = sort(scores ./ normalFrameF, 'descend');
    
    for k=1:6
        currSiftMatFile = strcat(frameBaseName, '_', num2str(idxs(k)), '.mat');
        [currentFrameName, featureCount, positions, ...
            orients, scales, descriptors] = loadOwnSiftDataOf(currSiftMatFile);
        img = imread(strcat('frames/',currentFrameName));
        subplot(2,3,k);
        imshow(img);
        tillIdx = regexpi(currentFrameName, '_');
        fraName = currentFrameName(tillIdx+1:end);
        tillIdx = regexpi(fraName, '.png');
        fraName = fraName(1:tillIdx-1);
        title(strcat('Matching Imgage ', fraName, ' with score: ',num2str(scores(k))));
    end
    
end